oldwd <- setwd("raw.data")
ciexyzCMF2.data <- read.csv(file="lin2012xyz2e_1_7sf.csv", comment.char = "#")
ciexyzCC2.data <- read.csv(file="cc2012xyz2_1_5dp.csv", comment.char = "#")
ciexyzCMF10.data <- read.csv(file="lin2012xyz10e_1_7sf.csv", comment.char = "#")
ciexyzCC10.data <- read.csv(file="cc2012xyz10_1_5dp.csv", comment.char = "#")
setwd(oldwd)
setwd("data")
save(ciexyzCMF2.data, ciexyzCMF10.data, ciexyzCC2.data, ciexyzCC10.data, file="ciexyz2006.data.rda")
setwd(oldwd)
